"use client";

import { ChakraProvider } from "@chakra-ui/react"
import { Inter } from "next/font/google"
import "./globals.css"
import theme from "./theme"
import Nav from "./navbar";

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraProvider theme={theme} cssVarsRoot="body">
          <Nav>
            {children}
          </Nav>
        </ChakraProvider>
      </body>
    </html>
  );
}
